# Generated by Django 5.0.6 on 2024-07-01 10:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core_Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiNhom',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('IsPhongBan', models.IntegerField(default=0)),
                ('TenLoaiNhom', models.CharField(max_length=255)),
                ('CreatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('IsActive', models.IntegerField(default=1)),
                ('CreatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LN_CreatedBy', to='Core_Account.users')),
                ('Parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LN_Parent', to='Core_Departments.loainhom')),
                ('UpdatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LN_UpdatedBy', to='Core_Account.users')),
            ],
            options={
                'db_table': 'LoaiNhom',
            },
        ),
        migrations.CreateModel(
            name='Nhom',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('TenNhom', models.CharField(max_length=255)),
                ('MaNhom', models.CharField(max_length=100)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('IsActive', models.IntegerField(default=1)),
                ('NienKhoa', models.IntegerField(null=True)),
                ('CreatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='N_CreatedBy', to='Core_Account.users')),
                ('LoaiNhom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core_Departments.loainhom')),
                ('Parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='N_Parent', to='Core_Departments.nhom')),
                ('UpdatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='N_UpdatedBy', to='Core_Account.users')),
            ],
            options={
                'db_table': 'Nhom',
            },
        ),
    ]
