# Generated by Django 5.0.6 on 2024-06-30 05:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('MaSinhVien', models.CharField(max_length=50, null=True)),
                ('Status', models.IntegerField(default=1)),
                ('CreateAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdateAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'SinhVien',
            },
        ),
        migrations.CreateModel(
            name='TuyenSinh',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('IdChuongTrinh', models.IntegerField()),
                ('IdLoaiHinhDaoTao', models.IntegerField()),
                ('IdHinhThucDaoTao', models.IntegerField()),
                ('IdTrangThaiHoc', models.IntegerField()),
                ('IdLoaiTotNghiep', models.IntegerField(null=True)),
                ('NgayChuyenTrangThaiHoc', models.DateField(null=True)),
                ('ChuyenNganh', models.IntegerField()),
                ('NgayNhapHoc', models.DateField(null=True)),
                ('KhoaDaoTao', models.IntegerField()),
                ('MaToHopTrungTuyen', models.CharField(null=True)),
                ('DiemTrungTuyen', models.FloatField(null=True)),
                ('MaMon1', models.CharField(null=True)),
                ('DiemMon1', models.FloatField(null=True)),
                ('MaMon2', models.CharField(null=True)),
                ('DiemMon2', models.FloatField(null=True)),
                ('MaMon3', models.CharField(null=True)),
                ('DiemMon3', models.FloatField(null=True)),
                ('DoiTuongUuTien', models.IntegerField(null=True)),
                ('KhuVucUuTien', models.CharField(null=True)),
                ('NamTotNghiepTHPT', models.IntegerField(null=True)),
                ('HocLuc', models.CharField(max_length=20, null=True)),
                ('HanhKiem', models.CharField(max_length=20, null=True)),
                ('MaTinhLop12', models.CharField(null=True)),
                ('MaQuanLop12', models.CharField(null=True)),
                ('MaTruongLop12', models.CharField(null=True)),
                ('DiemTBLop12', models.FloatField(null=True)),
                ('Status', models.IntegerField(default=1)),
                ('CreateAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdateAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('SinhVien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TuyenSinh', to='Core_Account.sinhvien')),
            ],
            options={
                'db_table': 'TuyenSinh',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('IdCard', models.CharField(max_length=100, null=True)),
                ('HoTen', models.CharField(max_length=100, null=True)),
                ('GioiTinh', models.IntegerField(null=True)),
                ('NgaySinh', models.DateField(null=True)),
                ('DanToc', models.IntegerField(null=True)),
                ('ThanhPhanXuatThan', models.CharField(max_length=225, null=True)),
                ('IdQuocTich', models.IntegerField(null=True)),
                ('TonGiao', models.CharField(max_length=100, null=True)),
                ('SDT', models.CharField(max_length=20, null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('CCCD', models.CharField(max_length=20, null=True)),
                ('NgayCapCCCD', models.DateField(max_length=20, null=True)),
                ('NoiCapCCCD', models.CharField(max_length=20, null=True)),
                ('NgayVaoDoan', models.DateField(null=True)),
                ('NgayVaoDang', models.DateField(null=True)),
                ('SoTk', models.CharField(null=True)),
                ('TenNganHang', models.CharField(null=True)),
                ('MaBaoHiem', models.CharField(null=True)),
                ('SoTheThuVien', models.CharField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.AddField(
            model_name='sinhvien',
            name='Users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core_Account.users'),
        ),
        migrations.CreateModel(
            name='LyLichBoSung',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('XepLoaiHocTap', models.IntegerField(null=True)),
                ('XepLoaiHanhKiem', models.IntegerField(null=True)),
                ('XepLoaiTotNghiep', models.IntegerField(null=True)),
                ('NamTotNghiep', models.IntegerField(null=True)),
                ('DiemThuong', models.FloatField(null=True)),
                ('LyDoThuongDiem', models.CharField(null=True)),
                ('HoTenCha', models.CharField(max_length=225, null=True)),
                ('QuocTichCha', models.IntegerField(null=True)),
                ('DanTocCha', models.IntegerField(null=True)),
                ('TonGiaoCha', models.IntegerField(null=True)),
                ('NamSinhCha', models.IntegerField(null=True)),
                ('HoKhauTTCha', models.CharField(max_length=500, null=True)),
                ('NgheNghiepCha', models.CharField(max_length=500, null=True)),
                ('HoTenMe', models.CharField(max_length=225, null=True)),
                ('QuocTichMe', models.IntegerField(null=True)),
                ('DanTocMe', models.IntegerField(null=True)),
                ('TonGiaoMe', models.IntegerField(null=True)),
                ('NamSinhMe', models.IntegerField(null=True)),
                ('HoKhauTTMe', models.CharField(max_length=500, null=True)),
                ('NgheNghiepMe', models.CharField(max_length=500, null=True)),
                ('HoTenVC', models.CharField(max_length=225, null=True)),
                ('QuocTichVC', models.IntegerField(null=True)),
                ('DanTocVC', models.IntegerField(null=True)),
                ('TonGiaoVC', models.IntegerField(null=True)),
                ('NamSinhVC', models.IntegerField(null=True)),
                ('HoKhauTTVC', models.CharField(max_length=500, null=True)),
                ('NgheNghiepVC', models.CharField(max_length=500, null=True)),
                ('ThongTinACE', models.CharField(max_length=1000, null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core_Account.users')),
            ],
            options={
                'db_table': 'LyLichBoSung',
            },
        ),
        migrations.CreateModel(
            name='DiaChi',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('DateStart', models.DateTimeField(null=True)),
                ('DateEnd', models.DateTimeField(null=True)),
                ('IdTinh', models.IntegerField(null=True)),
                ('IdHuyen', models.CharField(max_length=100, null=True)),
                ('IdXa', models.IntegerField(null=True)),
                ('ThonXom', models.CharField(max_length=100, null=True)),
                ('Type', models.IntegerField(null=True)),
                ('Status', models.IntegerField(default=1)),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Core_Account.users')),
            ],
            options={
                'db_table': 'DiaChi',
            },
        ),
    ]
