# Generated by Django 5.0.6 on 2024-07-01 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core_Departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhom',
            name='Expired',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loainhom',
            name='Parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LN_Parent', to='Core_Departments.loainhom'),
        ),
        migrations.AlterField(
            model_name='nhom',
            name='NienKhoa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nhom',
            name='Parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='N_Parent', to='Core_Departments.nhom'),
        ),
    ]
